
// Register a new user
POST https://innovative-learning-api-e73228a278b9.herokuapp.com/users/register HTTP/1.1
content-type: application/json

{
  "email": "hazem@gmail.com",
  "password": "100100",
  "firstName": "Hazem",
  "lastName": "Magdy",
  "dateOfBirth": "19-6-1989",
  "role": "admin"
}

###


// Login with user credentials
POST https://innovative-learning-api-e73228a278b9.herokuapp.com/auth/login HTTP/1.1
content-type: application/json

{
  "email": "hazem@gmail.com",
  "password": "100100",
}

###


// After a successful login, Create a new course if the user is instructor
POST https://innovative-learning-api-e73228a278b9.herokuapp.com/courses/create HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg0ZmJmZTk3ZTZkYmRmYTdlYmIwMjEiLCJlbWFpbCI6ImhhemVtMDAxMEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTk5OTE0NTYsImV4cCI6MTcyMDA3Nzg1NiwiYXVkIjoiNjY4NGZiZmU5N2U2ZGJkZmE3ZWJiMDIxIiwiaXNzIjoiSW5ub3ZhdGl2ZUxlYXJuaW5nUGxhdGZvcm0ifQ.Glc9ili96d6NaczQLo8Ra-sRJph0F62j_wCaRsHGipI



###


// List all published courses (public endpoint)
GET http://https://innovative-learning-api-e73228a278b9.herokuapp.com/courses HTTP/1.1
content-type: application/json


###


// List all published courses (public endpoint)
GET  https://innovative-learning-api-e73228a278b9.herokuapp.com/courses/6685376e16a7e5eba702eb37 HTTP/1.1
content-type: application/json
Authorization: Bearer <....>


###

// List all published courses (public endpoint)
PUT  http://{{$dotenv ONLINE_API_URL}}/courses/6685376e16a7e5eba702eb37/publish HTTP/1.1
content-type: application/json
Authorization: 


###


